### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by austince** [bechurch/reverse-proxy-demo#2]
Hi there, thanks for the great tool + walkthrough. Do you have any idea how long it would take to add simple SSL support for HTTPS? I need a quick way to test something w/an SSL reverse proxy but would rather not spend the time putting together a docker/ nginx one.

**Comment by bnchrch** [comment]
This should handle SSL requests no problem! Are you seeing something different @austince

**Comment by austince** [comment]
Oops, missed this. Must've either figured out what I was doing wrong or given up! Thanks @bechurch
